FROM cirrusci/flutter:stable AS build

WORKDIR /app

COPY . .

RUN flutter pub get
RUN flutter build web --release

FROM nginx:alpine

# remove página padrão
RUN rm -rf /usr/share/nginx/html/*

# copia o build gerado
COPY --from=build /app/build/web /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
