FROM maven:3.9.6-eclipse-temurin-21 AS builder
WORKDIR /backend

COPY ../pom.xml ./pom.xml
COPY . ./api-denuncia
RUN mvn -pl api-denuncia -am clean package -DskipTests

FROM eclipse-temurin:21-jre
WORKDIR /backend

COPY --from=builder /backend/api-denuncia/target/*.jar app.jar
CMD ["java", "-jar", "app.jar"]
